apiVersion: v1
kind: Pod
metadata:
  name: service-5-pod
  labels:
    app: service-5
spec:
  containers:
    - name: service-5-container
      image: jpcqaa/servicio5s:latest
      ports:
        - containerPort: 4001

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-5-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4001
      protocol: TCP
  selector:
    app: service-5