apiVersion: v1
kind: Pod
metadata:
  name: servicio-3-pod
  labels:
    app: servicio-3
spec:
  containers:
    - name: servicio-3-container
      image: nicolort/app-jskoa:latest
      ports:
        - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-3-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
  selector:
    app: servicio-3