apiVersion: v1
kind: Pod
metadata:
  name: servicio-1-pod
  labels:
    app: servicio-1
spec:
  containers:
    - name: servicio-1-container
      image: davidtovarmontoya/servicio-1:latest
      ports:
        - containerPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-1-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: servicio-1